#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 1200
#define WINDOW_HEIGHT 800

#define SIMULATION_WIDTH 900
#define SIMULATION_HEIGHT 800
#define INVENTORY_WIDTH 300

#define TARGET_FPS 60
#define FRAME_DELAY_MS 16

#define MAX_SPECIES 20
#define MAX_INDIVIDUALS 2000
#define MAX_FOOD_SOURCES 100

#define DEFAULT_TARNISHED_COUNT 50
#define DEFAULT_MISBEGOTTEN_COUNT 25
#define DEFAULT_DEMIGOD_COUNT 8

#define SIMULATION_SPEED_MIN 1
#define SIMULATION_SPEED_MAX 5
#define SIMULATION_SPEED_START 1

#define SPRITE_SIZE 32
#define COLLISION_DISTANCE_SQUARED 900

#define MIN_REPRODUCTION_AGE 600
#define REPRODUCTION_COOLDOWN 1800

#endif